title: Chandra Kanth
logo: /assets/img/Chandra Kanth Kurni.png
description: M.Tech(Computer Science) Post graduate with 4+ Years hands on experience in Data Science & SAP ABAP technologies which involved in solving complex business problems by leveraging AI & ML. Focus areas include CRM,OCR and Healthcare Technologies.
show_downloads: true
theme: jekyll-theme-minimal
