title: Chandra Kanth
logo: /assets/img/KCK.JPEG
#logo: https://media.licdn.com/dms/image/D5603AQFIw7Emsx7UwA/profile-displayphoto-shrink_200_200/0/1713560048102?e=1719446400&v=beta&t=51435fU9DLmcwrrLeGIbcT_5aoaGNwWugApRvjH9V9A
description: Data Scientist @ Cognier Insights Pvt Ltd
show_downloads: true
theme: jekyll-theme-minimal
