title: Chandra Kanth
logo: /assets/img/KCK.png {: .align-center}
# description: Looking for a challenging position in Data Science environment that will offer the opportunity for both professional and personal growth as well as to utilize my abilities and experience.
show_downloads: true
theme: jekyll-theme-minimal
